dist: xenial
language: python
python:
  - "3.7"
before_install:
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  - sudo apt-get install -y nodejs
install:
  - pip install pre-commit
script:
  - pre-commit run --all-files
